#!/bin/bash -evx

cat <<EOF > ./chroot/home/$HMRISO_USER/build-dwm
#!/bin/bash -e

cd /home/$HMRISO_USER/
git clone https://github.com/marigostra/dwm/
mv dwm .dwm
cd .dwm
git branch homeros origin/homeros
git checkout homeros
make 
EOF

chmod 755 ./chroot/home/$HMRISO_USER/build-dwm
in-chroot  /home/$HMRISO_USER/build-dwm
rm -f ./chroot/home/$HMRISO_USER/build-dwm
chown -R 1000:1000 ./chroot/home/$HMRISO_USER/.dwm
