#!/bin/bash -evx

cat <<EOF > ./chroot/etc/voiceman.conf
# VoiceMan configuration for LUWRAIN distribution
# Michael Pozhidaev <michael.pozhidaev@gmail.com>

[Global]
inet socket port = 5511
socket = "/tmp/voiceman.socket"
log level = info
default language = rus

[characters]
rus = "0123456789.,;:_-+=[]&<>""'/\\|?~\`!@#\$%^*(){}"
EOF

cat <<EOF > ./chroot/etc/voiceman.d/rhvoice-rus.output
[output]
name = RHVoice-rus
type = command
lang = rus
synth command = "RHVoice -r %r -p %p | voiceman-trim --words"
alsa player command = "exec aplay -"
pitch num digits after dot = 2
pitch min = "0.1"
pitch aver = 1
pitch max = "1.9"
rate num digits after dot = 2
rate max = "0.5"
rate aver = 1.6
rate min = 2
EOF

#cat <<EOF > ./chroot/etc/voiceman.d/rhvoice-eng.output
#[output]
#name = RHVoice-eng
#type = command
#lang = eng
#synth command = "RHVoice -r %r -p %p | voiceman-trim --words"
#alsa player command = "exec aplay -"
#pitch num digits after dot = 2
#pitch min = "0.1"
#pitch aver = 1
#pitch max = "1.9"
#rate num digits after dot = 2
#rate max = "0.5"
#rate aver = 1.6
#rate min = 2
#EOF

cat <<EOF > ./chroot/etc/voiceman.d/rhvoice-eng.output
[output]
name = espeak
type = command
lang = eng
synth command = "espeak --stdout -p %p -s %r -a %v | voiceman-trim --words"
alsa player command = "exec aplay -t raw -f s8 -c 1 -r 22500"
#replacements = "/usr/share/espeak-data/replacements"
pitch num digits after dot = 0
pitch min = 1
pitch aver = 30
pitch max = 199
rate num digits after dot = 0
rate min = 200
rate aver = 160
rate max = 1
volume num digits after dot = 0
volume min = 0
volume aver = 100
volume max = 150
cap list = "a eigh b bee c see d dee e ee f ef g gee h eighch i ei j jay k kay l el m em n en o oh p pee q quu r ar s es t tee u ou v vee w doubloo x ecs y why z zet"
EOF

cat <<EOF > ./chroot/usr/share/voiceman/chars-table
0:ноль
1:один
2:два
3:три
4:четыре
5:пять
6:шесть
7:семь
8:восемь
9:девять
.:точка
,:запятая
;:точка с запятой
_:подчёркивание
-:дефис
+:плюс
=:равно
[:левая квадратная
]:правая квадратная
&:амперсанд
<:меньше
>:больше
"""":двойные кавычки
':апостроф
/:черта в гору
\\:черта с горы
|:вертикальная черта
?:вопросительный знак
~:тильда
\`:обратный апостроф
!:восклицательный знак
@:собачка
"#":диез
\$:знак доллара
%:процент
^:возведение в степень
*:звезда
(:левая круглая
):правая круглая
{:левая фигурная
}:правая фигурная
":":двоеточие
ъ:твёрдый знак
Ъ:твёрдый знак
ь:мягкий знак
Ь:мягкий знак
й:и краткое
Й:и краткое
EOF
