#!/bin/bash -evx

cat <<EOF > ./chroot/etc/emacspeak.conf
# emacspeak configuration

export DTK_PROGRAM=/usr/bin/voiceman-emacspeak
export DTK_TCL=tcl
export DTK_PORT=none
export DTK_DEVICE="espeak"
EOF

cat <<EOF > ./chroot/home/luwrain/.emacs

(setq user-mail-address "michael.pozhidaev@gmail.com")
(setq user-full-name "Michael Pozhidaev")

(global-set-key [f2] 'save-buffer)
(global-set-key [f3] 'find-file)
(global-set-key [f4] 'kill-buffer)
(global-set-key [f5] 'other-window)
(global-set-key [f6] 'calendar)
(global-set-key [f7] 'gnus)
(global-set-key [f8] 'w3m-browse-url)
(global-set-key [f9] 'compile)
(global-set-key [f10] 'switch-to-buffer)
(global-set-key [S-f3] 'shell-command)
(global-set-key [S-f4] 'shell)

(setq make-backup-files nil)

(setq inhibit-startup-screen t)
(setq line-move-visual nil)
(setq emacspeak-gnus-punctuation-mode 'all)
(setq emacspeak-message-punctuation-mode 'all)
(setq dtk-unicode-untouched-charsets '(ascii cyrillic-iso8859-5 latin-iso8859-1))
(setq kill-buffer-query-functions nil)

(require 'message)
(setq mm-coding-system-priorities '(koi8-r))
(add-to-list 'mm-body-charset-encoding-alist '(koi8-r . 8bit))
(setq message-cite-function 'message-cite-original-without-signature)
(setq smtpmail-default-smtp-server "localhost")
(setq send-mail-function 'smtpmail-send-it)
(require 'smtpmail)

(require 'w3m)
(setq mm-text-html-renderer 'w3m-standalone)
(remove-hook 'w3m-after-cursor-move-hook 'w3m-print-this-url)
(remove-hook 'w3m-after-cursor-move-hook 'w3m-show-form-hint)

(remove-hook 'w3m-after-cursor-move-hook 'w3m-highlight-current-anchor)
(remove-hook 'w3m-after-cursor-move-hook 'w3m-auto-show)

(setq browse-url-browser-function 'w3m-browse-url)
(setq w3m-search-engine-alist
      '(
        ("google" "http://www.google.ru/search?q=%s&hl=ru&ie=koi8-r" koi8-r)
        ))
(setq w3m-search-default-engine "google")
(setq w3m-use-cookies t)

(require 'dired-x)
(add-hook 'dired-mode-hook
	  (lambda ()
	    (setq dired-omit-files-p t)
	    (setq dired-omit-extensions '("~" ".o" ".a" ".la" ".toc" ".aux" ".log"))
	    (setq dired-omit-files "^\\\\.")
))
EOF

chown 1000:1000 ./chroot/home/luwrain/.emacs

pushd ./chroot/usr/share/emacs/site-lisp/emacspeak/lisp
cat <<EOF | patch -p1
diff -ur orig/dtk-speak.el new/dtk-speak.el
--- orig/dtk-speak.el	2016-03-07 20:34:08.543543849 +0600
+++ new/dtk-speak.el	2016-03-07 20:35:15.187542726 +0600
@@ -1517,8 +1517,9 @@
   (declare (special dtk-character-to-speech-table))
   (if  (eq (char-charset char) 'ascii)
       (aref dtk-character-to-speech-table char )
-    (or (dtk-unicode-short-name-for-char char)
-        (format "octal %o"  char ))))
+      (format "%c" char)))
+;;    (or (dtk-unicode-short-name-for-char char)
+;;        (format "octal %o"  char ))))
 
 ;;}}}
 ;;{{{  interactively selecting the server:
@@ -1884,7 +1885,7 @@
           (when pronunciation-table
             (tts-apply-pronunciations
              pronunciation-table))
-          (dtk-unicode-replace-chars mode)
+;;          (dtk-unicode-replace-chars mode)
           (dtk-handle-repeating-patterns mode)
           (dtk-quote mode))
         (goto-char (point-min))
diff -ur orig/emacspeak-speak.el new/emacspeak-speak.el
--- orig/emacspeak-speak.el	2016-03-07 20:34:08.543543849 +0600
+++ new/emacspeak-speak.el	2016-03-08 00:55:16.151280008 +0600
@@ -762,7 +762,7 @@
      "sEnterregular expression to match lines that are decorative ASCII: ")
 
 (defcustom emacspeak-unspeakable-rule
-  "^[^0-9a-zA-Z]+\$"
+  "^\\\\W+\$"
   "*Pattern to match lines of special chars.
 This is a regular expression that matches lines containing only
 non-alphanumeric characters.  emacspeak will generate a tone
@@ -1055,7 +1055,7 @@
     (cond
      ((emacspeak-is-alpha-p char) (dtk-letter (char-to-string
                                                char )))
-     ((> char 128) (emacspeak-speak-char-name char))
+;;     ((> char 128) (emacspeak-speak-char-name char))
      (t (dtk-dispatch (dtk-char-to-speech char ))))))
 ;;;###autoload
 (defun emacspeak-speak-char (&optional prefix)
@@ -1067,7 +1067,7 @@
     (when char
       (cond
        ((stringp display) (dtk-speak display))
-       ((> char 128) (emacspeak-speak-char-name char))
+;;       ((> char 128) (emacspeak-speak-char-name char))
        ((and (not prefix)
              (emacspeak-is-alpha-p char))
         (dtk-speak (emacspeak-get-phonetic-string char )))
@@ -1082,14 +1082,14 @@
     (when char
       (cond
        ((stringp display) (dtk-speak display))
-       ((> char 128) (emacspeak-speak-char-name char))
+;;       ((> char 128) (emacspeak-speak-char-name char))
        (t (emacspeak-speak-this-char char))))))
 
 ;;;###autoload
 (defun emacspeak-speak-char-name (char)
   "tell me what this is"
   (interactive)
-  (dtk-speak (dtk-unicode-name-for-char char)))
+  (dtk-speak (format "%c" char)))
 
 ;;}}}
 ;;{{{ emacspeak-speak-display-char
EOF
popd

pushd ./chroot/usr/share/
for i in dtk-speak emacspeak-speak; do
rm -f ./emacs24/site-lisp/emacspeak/lisp/$i.elc
cp ./emacs/site-lisp/emacspeak/lisp/$i.el ./emacs24/site-lisp/emacspeak/lisp/
done
popd


