#!/bin/bash -evx

CHANNELS_DIR=$LWRISO_ROOT/opt/luwrain/i18n/ru/org/luwrain/speech/channels/
mkdir -p $CHANNELS_DIR
pushd $CHANNELS_DIR

mkdir -p 1 2 3 

cat <<EOF > 1/strings.txt
"type" = "voiceman"
"name" = "VoiceMan speech server"
EOF
cat <<EOF > 1/booleans.txt
"default" = "true"
EOF

cat <<EOF > 2/strings.txt
"type" = "command"
"name" = "RHVoice"
"to-speakers-command" = "RHVoice -r 1.6 | aplay"
EOF
cat <<EOF > 2/booleans.txt
"default" = "false"
"signed" = "false"
"big-endian" = "false"
EOF
cat <<EOF > 2/integers.txt
"default-pitch" = "50"
"default-pitch" = "50"
"sample-rate" = "16000"
"sample-size" = "16"
"num-channels" = "1"
EOF

cat <<EOF > 3/strings.txt
"type" = "command"
"name" = "RHVoice (books)"
"to-stream-command" = "RHVoice -r 1.6 | sox -t wav - -t raw -"
EOF
cat <<EOF > 3/booleans.txt
"default" = "false"
"signed" = "false"
"big-endian" = "false"
EOF
cat <<EOF > 3/integers.txt
"default-pitch" = "50"
"default-pitch" = "50"
"sample-rate" = "16000"
"sample-size" = "16"
"num-channels" = "1"
EOF

popd
