#!/bin/bash -evx

cat <<EOF > $LWRISO_ROOT/home/luwrain/.xinitrc
# Put the actions you would like to run on X.org launch

exec &> /tmp/xinitrc.log
export LANG=en_US.UTF-8
setxkbmap -layout "us,ru"
setxkbmap -option "grp:alt_shift_toggle,grp_led:scroll"
exec ogg123 -d alsa /opt/homeros.ogg
EOF
