#!/bin/bash -evx

# brltty
sed  -i -e s/'^RUN_BRLTTY=.*$'/'RUN_BRLTTY=yes'/ ./chroot/etc/default/brltty
# Russian only
sed  -i -e s/'^ARGUMENTS=.*$'/'ARGUMENTS="-q -t ru"'/ ./chroot/etc/default/brltty
sed -i -e s/'^.*text-table.*Russian.*$'/'text-table ru'/ ./chroot/etc/brltty.conf

#ln -s /usr/lib/jni/libbrlapi_java.so $LWRISO_ROOT/home/luwrain/luwrain/jni/libbrlapi_java.so
ln -s /usr/lib/jni/libbrlapi_java.so $LWRISO_ROOT/opt/luwrain/jni/libbrlapi_java.so
