#!/bin/bash -evx

cd /iso
. config.sh

cat <<EOF > /etc/apt/sources.list
deb http://download.luwrain.org/ubuntu/ xenial main
deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
deb http://ru.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
EOF

echo "nameserver $LWRISO_NAMESERVER" > /run/resolvconf/resolv.conf
apt-get update
apt-get -y --force-yes install syslinux syslinux-common syslinux-utils squashfs-tools genisoimage

mksquashfs chroot disk/casper/filesystem.squashfs -comp xz > /dev/null

rm -rf disk/casper/filesystem.squashfs.gpg disk/md5sum.txt disk/pool disk/ubuntu 
echo "Homeros - Release $HMRISO_ARCH ($HMRISO_DATE)" > disk/.disk/info

pushd disk
find -type f | while read l; do
md5sum "$l"
done > ../md5sum.txt
popd 
mv md5sum.txt disk

mkisofs -r -V "Homeros $HMRISO_ARCH $(date --iso-8601)" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o homeros.iso disk/ 2> /dev/null 
isohybrid homeros.iso

# ISO compiled!
